POST localhost:8080/residents HTTP/1.1
Content-Type: application/json

{
  "residentSerialNumber": 12,
  "name": "똥개",
  "residentRegistrationNumber": "981108-2333333",
  "genderCode": "여",
  "birthDate": "1998-11-08 22:54:00",
  "birthPlaceCode": "병원",
  "registrationBaseAddress": "주소"
}
###

PUT localhost:8080/residents/12
Content-Type: application/json

{
  "name": "하이",
  "residentRegistrationNumber": "981108-1232324",
  "genderCode": "남",
  "birthDate": "1998-11-08 22:54:00",
  "birthPlaceCode": "길거리",
  "registrationBaseAddress": "인천시 계양구"
}